name: gnome-taquin
adopt-info: gnome-taquin
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  gnome-taquin:
    interface: dbus
    bus: session
    name: org.gnome.Taquin

apps:
  gnome-taquin:
    extensions: [ gnome-3-38 ]
    command: usr/bin/gnome-taquin
    desktop: usr/share/applications/org.gnome.Taquin.desktop
    environment:
      PATH: $SNAP/usr/games:$PATH

parts:
  gnome-taquin:
    source: https://gitlab.gnome.org/GNOME/gnome-taquin.git
    source-type: git
    source-tag: '3.38.1'
    parse-info: [usr/share/metainfo/org.gnome.Taquin.appdata.xml]
    override-build: |
      sed -i.bak -e 's|=gnome-taquin$|=${SNAP}/meta/gui/org.gnome.Taquin.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Taquin.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/hicolor/scalable/org.gnome.Taquin.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Taquin.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-taquin/current/usr]
    organize:
      snap/gnome-taquin/current/usr: usr
    build-packages:
     - intltool
     - yelp-tools
